name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  standard:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "windows-2022"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install wheel
      run: pip install wheel

    - name: Install package
      run: python -m pip install -e .[test]

    - name: Run sw_core_data_types package tests
      run: |
        python -m unittest discover --verbose sw_core_data_types\src\sw_core

    - name: Run sw_core_parameters package tests
      run: |
        python -m unittest discover --verbose sw_core_parameters\src\sw_core
